name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version: [1.65.0, stable, nightly]

    name: tests / ${{ matrix.version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          toolchain: ${{ matrix.version }}

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql user: 'ci'
          mysql password: 'ci'

      - run: cargo test
        env:
          DATABASE_URL: mysql://ci:ci@127.0.0.1:3306
